# -----------------------------------Set Up------------------------------------
variables:
    PY_VERSION: 2
    TMPDIR: ./tmp
    VENV: pysitk-test-py${PY_VERSION}
    ITK_DIR: /mnt/shared/mebner/environment/ITK/ITK_NiftyMIC-python${PY_VERSION}-build
    FSL_DIR: /usr/share/fsl/5.0
    NIFTYREG_INSTALL: /mnt/shared/mebner/environment/NiftyReg/NiftyReg-master-install
    CONVERT3D_INSTALL: /mnt/shared/mebner/environment/Convert3D/c3d-git-install

before_script:
    # add NiftyReg to PATH
    - export PATH="${NIFTYREG_INSTALL}/bin:$PATH"

    # add FSL
    - FSL_DIR="/usr/share/fsl/5.0"
    - . ${FSL_DIR}/etc/fslconf/fsl.sh
    - PATH=${FSL_DIR}/bin:${PATH}
    - export FSL_DIR PATH

    # add Convert3D to PATH
    - export PATH="${CONVERT3D_INSTALL}/bin:$PATH"

    # save current folder path
    - cwd_dir=$(pwd)

    # create virtual environment
    - rm -rf ${VENV}
    - mypython=$(which python${PY_VERSION})
    - virtualenv -p $mypython ${VENV}
    - cd ${VENV}
    - venv_dir=$(pwd)
    - source bin/activate
    
    # print Python version to CI output
    - which python
    - python --version

    # copy ITK_NiftyMIC-build WrapITK to site-packages of python venv
    - py_sitepkg=${venv_dir}/lib/python*/site-packages
    - cp -v ${ITK_DIR}/Wrapping/Generators/Python/WrapITK.pth ${py_sitepkg}

    # add CI_JOB_TOKEN for cloning dependent repositories in requirements.txt
    # (https://docs.gitlab.com/ee/user/project/new_ci_build_permissions_model.html#dependent-repositories)
    - cd $cwd_dir
    - sed -i -- "s/cmiclab/gitlab-ci-token:${CI_JOB_TOKEN}@cmiclab/g" requirements.txt

    # install requirements
    - pip install -r requirements.txt

    # set environment variables for installation
    - export NIFTYMIC_ITK_DIR=$ITK_DIR

    # run installation
    - pip install -e .

after_script:
    # delete tmp-directory
    - rm -rfv ${TMPDIR}

# ----------------------------------Test Jobs----------------------------------
builddocs:
  # only:
  #   - master
  script:
    - cd doc
    - doxygen doxyfile
  tags:
    - gift-adelie

reconstruct_volume:
  # only:
  #   - master
  script:
    - python niftymic_reconstruct_volume.py --dir-input /home/mebner/data/FetalBrain/input_data --dir-output ${TMPDIR} --verbose 0 --two-step-cycles 1
  tags:
    - gift-adelie

reconstruct_volume_from_slices:
  # only:
  #   - master
  script:    
    - python niftymic_reconstruct_volume_from_slices.py --dir-input /home/mebner/data/FetalBrain/motion_correction_oriented --reconstruction-space /home/mebner/data/FetalBrain/SRR_stacks3_TK1_lsmr_alpha0p03_itermax10_oriented.nii.gz --dir-output ${TMPDIR} --verbose 0
  tags:
    - gift-adelie  
