# -----------------------------------Set Up------------------------------------
variables:
    PY_VERSION: 3
    PRIVATE: 0
    TMPDIR: ./tmp
    DATADIR: /home/mebner/data/ci/FetalBrain
    VENV: pysitk-test-py${PY_VERSION}
    ITK_DIR: /mnt/shared/mebner/environment/ITK/ITK_NiftyMIC-python${PY_VERSION}-build
    FSL_DIR: /mnt/shared/mebner/environment/FSL/fsl
    TEST_DIR: /home/mebner/Development/NiftyMIC/data/tests
    NIFTYREG_INSTALL: /mnt/shared/mebner/environment/NiftyReg/NiftyReg-master-install
    CONVERT3D_INSTALL: /mnt/shared/mebner/environment/Convert3D/c3d-git-install

before_script:
    # add NiftyReg to PATH
    - export PATH="${NIFTYREG_INSTALL}/bin:$PATH"

    # add FSL
    - PATH=${FSL_DIR}/bin:${PATH}
    - export PATH="${FSL_INSTALL}/bin:$PATH"
    - export FSLOUTPUTTYPE=NIFTI_GZ

    # add Convert3D to PATH
    - export PATH="${CONVERT3D_INSTALL}/bin:$PATH"

    # save current folder path
    - cwd_dir=$(pwd)

    # create virtual environment
    - rm -rf ${VENV}
    - mypython=$(which python${PY_VERSION})
    - virtualenv -p $mypython ${VENV}
    - cd ${VENV}
    - venv_dir=$(pwd)
    - source bin/activate
    
    # print Python version to CI output
    - which python
    - python --version

    # copy ITK_NiftyMIC-build WrapITK to site-packages of python venv
    - py_sitepkg=${venv_dir}/lib/python*/site-packages
    - cp -v ${ITK_DIR}/Wrapping/Generators/Python/WrapITK.pth ${py_sitepkg}

    - cd $cwd_dir
    # If PRIVATE is used:
    # add CI_JOB_TOKEN for cloning dependent repositories in requirements.txt
    # (https://docs.gitlab.com/ee/user/project/new_ci_build_permissions_model.html#dependent-repositories)
    - >
      (if [ ${PRIVATE} == 1 ];
      then sed -i -- "s#github.com/gift-surg#gitlab-ci-token:${CI_JOB_TOKEN}@PRIVATE.cs.ucl.ac.uk/GIFT-Surg#g" requirements.txt;
      fi);
    # install requirements
    - pip install -r requirements.txt

    # set environment variables for installation
    - export NIFTYMIC_ITK_DIR=$ITK_DIR

    # run installation
    - pip install -e .

    # replace TEST_DIR in niftymic/definitions.py file
    - sed -i -- 's:DIR_TEST = os.path.join(DIR_ROOT, "data", "tests"):DIR_TEST = "'"$TEST_DIR"'":g' niftymic/definitions.py
    - cat niftymic/definitions.py

after_script:
    # delete tmp-directory
    - rm -rfv ${TMPDIR}

# ----------------------------------Test Jobs----------------------------------
builddocs:
  # only:
  #   - master
  script:
    - cd doc
    - doxygen doxyfile
  tags:
    - gift-adelie

installation:
  only:
    - dev
    # - master
  script:
    - python -m nose tests/installation_test.py
  tags:
    - gift-adelie

reconstruct_volume_tk1l2:
  # only:
  #   - master
  script:
    - >
      niftymic_reconstruct_volume
      --filenames ${DATADIR}/input_data/axial.nii.gz ${DATADIR}/input_data/coronal.nii.gz ${DATADIR}/input_data/sagittal.nii.gz
      --output ${TMPDIR}/srr_from_slices_tk1l2.nii.gz
      --suffix-mask _mask
      --verbose 0 
      --isotropic-resolution 2
      --reconstruction-type TK1L2
      --two-step-cycles 1
      --iter-max 2
      --iter-max-first 2
  tags:
    - gift-adelie

reconstruct_volume_huberl2:
  # only:
  #   - master
  script:
    - >
      niftymic_reconstruct_volume
      --filenames ${DATADIR}/input_data/axial.nii.gz ${DATADIR}/input_data/coronal.nii.gz ${DATADIR}/input_data/sagittal.nii.gz 
      --output ${TMPDIR}/srr_from_slices_huberl2.nii.gz
      --suffix-mask _mask
      --verbose 0 
      --isotropic-resolution 2
      --reconstruction-type HuberL2
      --two-step-cycles 1
      --iter-max 2
      --iter-max-first 2
      --iterations 1
  tags:
    - gift-adelie

reconstruct_volume_from_slices:
  # only:
  #   - master
  script:    
    - >
      niftymic_reconstruct_volume_from_slices
      --filenames ${DATADIR}/input_data/axial.nii.gz ${DATADIR}/input_data/coronal.nii.gz ${DATADIR}/input_data/sagittal.nii.gz 
      --dir-input-mc ${DATADIR}/motion_correction_oriented
      --suffix-mask _mask
      --reconstruction-space ${DATADIR}/SRR_stacks3_TK1_lsmr_alpha0p03_itermax10_oriented.nii.gz 
      --output ${TMPDIR}/srr_from_slices.nii.gz
      --verbose 0
      --isotropic-resolution 2
      --iter-max 2
  tags:
    - gift-adelie  

run_reconstruction_pipeline:
  # only:
  #   - master
  script:
    - >
      niftymic_run_reconstruction_pipeline
      --filenames ${DATADIR}/input_data/axial.nii.gz
      --filenames-masks ${DATADIR}/input_data/axial_mask.nii.gz
      --dir-output ${TMPDIR} 
      --suffix-mask _mask
      --bias-field-correction 1
      --two-step-cycles 0
      --iter-max 1
      --run-diagnostics 1
      --slice-thicknesses 3.85
      --verbose 0 
  tags:
    - gift-adelie

param_study_huberl2:
  # only:
  #   - master
  script:
    - recon_type=HuberL2
    - >
      niftymic_run_reconstruction_parameter_study
      --filenames ${DATADIR}/input_data/axial.nii.gz ${DATADIR}/input_data/coronal.nii.gz ${DATADIR}/input_data/sagittal.nii.gz 
      --dir-input-mc ${DATADIR}/motion_correction_oriented
      --suffix-mask _mask
      --reference ${DATADIR}/SRR_stacks3_TK1_lsmr_alpha0p03_itermax10_oriented.nii.gz 
      --dir-output ${TMPDIR}/param_study 
      --alphas 0.01 0.05 
      --iter-max 2 
      --verbose 0 
      --iterations 2
      --reconstruction-type ${recon_type} 
  tags:
    - gift-adelie

# rsfmri_estimate_motion:
#   # only:
#   #   - master
#   script:
#     - recon_type=HuberL2
#     - >
#       python niftymic/prototyping/rsfmri_estimate_motion.py
#       --filename ${DATADIR}/rsfmri/bold.nii.gz
#       --filename-mask ${DATADIR}/rsfmri/bold_4Dmask.nii.gz
#       --dir-output ${TMPDIR}/rsfmri 
#       --two-step-cycles 1
#       --iterations 2
#       --sda
#       --alpha 1
#       --verbose 0 
#       --prototyping
#   tags:
#     - gift-adelie

# rsfmri_reconstruct_volume_from_slices:
#   # only:
#   #   - master
#   script:
#     - recon_type=TK1L2
#     - >
#       python niftymic/prototyping/rsfmri_reconstruct_volume_from_slices.py
#       --filename ${DATADIR}/rsfmri/bold.nii.gz
#       --filename-mask ${DATADIR}/rsfmri/bold_4Dmask.nii.gz
#       --output ${TMPDIR}/rsfmri/foo.nii.gz 
#       --alpha 0.05
#       --iter-max 2 
#       --verbose 0 
#       --reconstruction-type ${recon_type} 
#       --reconstruction-spacing 2 2 5
#       --use-masks-srr 1
#       --prototyping
#   tags:
#     - gift-adelie

##
# Results can (slightly) change depending on the downloaded library version;
# enough so that the accuracy limits are not met. Run them locally instead.
# unit_tests:
#   # only:
#   #   - master
#   script:
#     - python -m nose tests/brain_stripping_test.py
#     - python -m nose tests/case_study_fetal_brain_test.py
#     - python -m nose tests/data_reader_test.py
#     - python -m nose tests/image_similarity_evaluator_test.py
#     - python -m nose tests/intensity_correction_test.py
#     - python -m nose tests/linear_operators_test.py
#     - python -m nose tests/niftyreg_test.py
#     - python -m nose tests/residual_evaluator_test.py
#     - python -m nose tests/segmentation_propagation_test.py
#     - python -m nose tests/simulator_slice_acquisition_test.py
#     - python -m nose tests/stack_test.py
#   tags:
#     - gift-adelie
