# -----------------------------------Set Up------------------------------------
variables:
    PY_VERSION: 2
    CMICLAB: 1
    TMPDIR: ./tmp
    DATADIR: /home/mebner/data/ci/FetalBrain
    VENV: pysitk-test-py${PY_VERSION}
    ITK_DIR: /mnt/shared/mebner/environment/ITK/ITK_NiftyMIC-python${PY_VERSION}-build
    FSL_DIR: /mnt/shared/mebner/environment/FSL/fsl
    NIFTYREG_INSTALL: /mnt/shared/mebner/environment/NiftyReg/NiftyReg-master-install
    CONVERT3D_INSTALL: /mnt/shared/mebner/environment/Convert3D/c3d-git-install

before_script:
    # add NiftyReg to PATH
    - export PATH="${NIFTYREG_INSTALL}/bin:$PATH"

    # add FSL
    - PATH=${FSL_DIR}/bin:${PATH}
    - export PATH="${FSL_INSTALL}/bin:$PATH"
    - export FSLOUTPUTTYPE=NIFTI_GZ

    # add Convert3D to PATH
    - export PATH="${CONVERT3D_INSTALL}/bin:$PATH"

    # save current folder path
    - cwd_dir=$(pwd)

    # create virtual environment
    - rm -rf ${VENV}
    - mypython=$(which python${PY_VERSION})
    - virtualenv -p $mypython ${VENV}
    - cd ${VENV}
    - venv_dir=$(pwd)
    - source bin/activate
    
    # print Python version to CI output
    - which python
    - python --version

    # copy ITK_NiftyMIC-build WrapITK to site-packages of python venv
    - py_sitepkg=${venv_dir}/lib/python*/site-packages
    - cp -v ${ITK_DIR}/Wrapping/Generators/Python/WrapITK.pth ${py_sitepkg}

    - cd $cwd_dir
    # If cmiclab is used:
    # add CI_JOB_TOKEN for cloning dependent repositories in requirements.txt
    # (https://docs.gitlab.com/ee/user/project/new_ci_build_permissions_model.html#dependent-repositories)
    - >
      (if [ ${CMICLAB} == 1 ];
      then sed -i -- "s#github.com/gift-surg#gitlab-ci-token:${CI_JOB_TOKEN}@cmiclab.cs.ucl.ac.uk/GIFT-Surg#g" requirements.txt;
      fi);
    # install requirements
    - pip install -r requirements.txt

    # set environment variables for installation
    - export NIFTYMIC_ITK_DIR=$ITK_DIR

    # run installation
    - pip install -e .

after_script:
    # delete tmp-directory
    - rm -rfv ${TMPDIR}

# ----------------------------------Test Jobs----------------------------------
builddocs:
  # only:
  #   - master
  script:
    - cd doc
    - doxygen doxyfile
  tags:
    - gift-adelie

installation:
  # only:
  #   - master
  script:
    - python -m nose tests/installation_test.py
  tags:
    - gift-adelie

reconstruct_volume_tk1l2:
  # only:
  #   - master
  script:
    - >
      niftymic_reconstruct_volume
      --dir-input ${DATADIR}/input_data 
      --dir-output ${TMPDIR} 
      --verbose 0 
      --isotropic-resolution 2
      --reconstruction-type TK1L2
      --two-step-cycles 1
      --iter-max 2
      --iter-max-first 2
  tags:
    - gift-adelie

run_reconstruction_pipeline:
  # only:
  #   - master
  script:
    - >
      niftymic_run_reconstruction_pipeline
      --filenames ${DATADIR}/axial.nii.gz
      --dir-output ${TMPDIR} 
      --gestational-age 33
      --bias-field-correction 1
      --two-step-cycles 0
      --iter-max 1
      --run-data-vs-simulated-data 0
      --verbose 0 
  tags:
    - gift-adelie


reconstruct_volume_huberl2:
  # only:
  #   - master
  script:
    - >
      niftymic_reconstruct_volume
      --dir-input ${DATADIR}/input_data 
      --dir-output ${TMPDIR} 
      --verbose 0 
      --isotropic-resolution 2
      --reconstruction-type HuberL2
      --two-step-cycles 1
      --iter-max 2
      --iter-max-first 2
      --iterations 1
  tags:
    - gift-adelie

reconstruct_volume_from_slices:
  # only:
  #   - master
  script:    
    - >
      niftymic_reconstruct_volume_from_slices
      --dir-input ${DATADIR}/motion_correction_oriented
      --reconstruction-space ${DATADIR}/SRR_stacks3_TK1_lsmr_alpha0p03_itermax10_oriented.nii.gz 
      --dir-output ${TMPDIR} 
      --verbose 0
      --isotropic-resolution 2
      --iter-max 2
  tags:
    - gift-adelie  

param_study_huberl2:
  # only:
  #   - master
  script:
    - recon_type=HuberL2
    - >
      niftymic_run_reconstruction_parameter_study
      --dir-input ${DATADIR}/motion_correction_oriented 
      --reference ${DATADIR}/SRR_stacks3_TK1_lsmr_alpha0p03_itermax10_oriented.nii.gz 
      --dir-output ${TMPDIR}/param_study 
      --alpha-range 0.01 0.05 2 
      --iter-max 2 
      --verbose 0 
      --iterations 2
      --reconstruction-type ${recon_type} 
  tags:
    - gift-adelie
