builddocs:
  # only:
  #   - master
  script:
    - cd doc
    - doxygen doxyfile
  tags:
    - gift-adelie

testjob:
  # only:
  #   - master
  script:
    # save PySiTK folder path just in case
    - export pysitk_dir=$(pwd)

    # create a virtual env to dev-test
    - pyversion=2
    - tmpdir=tmp
    - venv="pysitk-test-py${pyversion}"
    - mypython=$(which python${pyversion})
    - virtualenv -p $mypython $venv
    - cd $venv
    - venv_dir=$(pwd)
    - source bin/activate
    
    # print Python version to CI output
    - which python
    - python --version

    # copy ITK_NiftyMIC-build WrapITK to site-packages of venv
    - itkpath=/mnt/shared/mebner/environment/ITK/ITK_NiftyMIC-python${pyversion}-build/Wrapping/Generators/Python/WrapITK.pth
    - pypath=${venv_dir}/lib/python*/site-packages
    - cp -v ${itkpath} ${pypath}

    # add CI_JOB_TOKEN for cloning dependent repositories in requirements.txt
    # (https://docs.gitlab.com/ee/user/project/new_ci_build_permissions_model.html#dependent-repositories)
    - cd $pysitk_dir
    - sed -i -- "s/cmiclab/gitlab-ci-token:${CI_JOB_TOKEN}@cmiclab/g" requirements.txt

    # install requirements
    - pip install -r requirements.txt
    - pip install -e .

    # 1) reconstruct_volume
    - python niftymic_reconstruct_volume.py \
    - --dir-input /home/mebner/data/FetalBrain/input_data \
    - --dir-output ${tmpdir} \
    - --verbose 0
    
    # 2) reconstruct_volume_from_slices
    - python niftymic_reconstruct_volume_from_slices.py \
    - --dir-input /home/mebner/data/FetalBrain/motion_correction_oriented \
    - --reconstruction-space /home/mebner/data/FetalBrain/SRR_stacks3_TK1_lsmr_alpha0p03_itermax10_oriented.nii.gz \
    - --dir-output ${tmpdir} \
    - --verbose 0

    # delete tmp-directory
    - rm -rf ${tmpdir}

  tags:
    - gift-adelie    