# Copyright 2020 Marta Bianca Maria Ranzini and contributors
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#     http://www.apache.org/licenses/LICENSE-2.0
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

device:
  num_workers: 4

training:
  seg_labels: [0, 1]
  inplane_size: [448, 512]
  spacing: [0.8, 0.8, -1.0]
  loss_type: "dynDiceCELoss"
  pow_dice: 1
  batch_size_train: 2
  batch_size_valid: 1
  nr_train_epochs: 10
  validation_every_n_epochs: 5
  sliding_window_validation: True
  lr: 1e-2
  manual_seed: 0
  model_to_load: null

output:
  max_nr_models_saved: 1
  val_image_to_tensorboad: False

log:
  message: "Training a 2D dynUNet with MONAI using Dice + Xent loss."
